### ISSUE TITLE
Time to consider a better organization of my server and its service.

### ISSUE THREAD

**Issue by crupest** [crupest/crupest#1]
I have had a Tencent Cloud VPS at HK for long as well as two domain, `crupest.life`, `crupest.space`.
I occasionally run some services on that server. However, I run some services from other places too. All the services are resolved under some domain or subdomain of above two.
Now I have to organize them, make some changes and prepare for future reuse.

# Prerequisites & Possessions

1. Tencent Cloud Lighthouse Server located at Hong Kong
2. Domain `crupest.life`
3. Domain `crupest.space`
4. GitHub Pages service

# Design

## Goals
1. Auto install, auto update and maybe auto uninstall.
  1.1. One script to install all on a fresh new system.
  1.2. One script to upgrade all services to latest.
2. Easy data backup and restore. Auto data backup regularly.
3. xxx

## Services
I will retain `crupest.life` domain and make `crupest.space` redirect to it. Then deprecate `space` domain and drop it so I won't pay for it.

1. `root`: Navigation page at domain root.
2. `code`: Code server.
3. `blog`: Long blog page.
4. `timeline`: My timeline app for microblog.
5. `mail`: Email server.

# Steps

## Software Stack
1. [Nginx](https://nginx.org) for reverse proxy and TLS of __all__ sites. [Certbot](https://certbot.eff.org) for TLS certifications.
2. For root domain, I'm going to use plain files served with nginx.
3. [code-server](https://github.com/coder/code-server) for code server.
4. I'm selecting a solution for blogs now. Candidates:
  4.1. A real app hosted on my server: maybe [halo](https://halo.run)
  4.2. Static sites generators: [Hugo](https://gohugo.io). (Currently used one)
  4.3. Write one on my own.
5. Mail system, maybe [docker-mailserver](https://docker-mailserver.github.io/docker-mailserver/edge/).

## Configs and Scripts

There is a bunch of config and script files. They can be committed to git repo for others to reference and for me to restore quickly when switching VPS.

1. Nginx and certbot configs.
2. Docker compose file for every docker based services.
3. Setup script.
4. Data backup scripts.

# TODO

- [x] Create my own code-server docker image.
- [x] Find out a way to deal with volume dir permission problems.
- [x] Migrate from caddy to nginx and certbot.
- [x] Fix the problem of mail server.
- [x] Change DNS resolutions.
- [x] URGENT: Add timeline to sites.
- [x] Maybe there is a better way to redirect http to https.
- [x] Test Certbot renew with dry run.
- [x] Test mail server.
- [x] ~Fix mail server PBL spam problem.~ Wait for dns update and test again later.
- [x] Test all pages.
- [x] Config nginx http body size limit.
- [x] Write data backup script.
- [x] Drop use of buggy rclone. Use Tencent cloud cli instead! 
- [x] Certbot auto renew.
- [x] Auto certbot dry run to test first.
- [x] ～Auto clean and update~. I can't `docker-compose` in container. So some actions must be performed externally.
- [x] SIGINT issue for sleep.
- [x] Implement crupest-api. Blocked by #4.
- [x] Auto backup support for ~checking last backup time~(always backup at restart in case I mess things up) and log backup.
- [x] ~Add config value validation.~ Too complicated.
- [x] Check ssl cert.
- [x] Compare file time to decide regeneration.
- [x] Add Nginx redirect template.
- [x] Redirect GitHub subdomain to my GitHub profile.
- [x] Fix Python version check.
- [x] ~Aio bash completion?~ No time.
- [x] ~Alias for tmux attach -t.~ Just run `tmux a`.
- [x] Fix aio git-update and up.
- [x] DNS template and generation.
- [x] Remove halo.
- [x] Restart nginx after generate nginx config.
- [x] ~Check template generate time to decide whether to update.~ Not a good idea.
- [x] #6 
- [x] ~Web hook.~ No need now. Blog is now auto generated and other things can be done with aio conveniently and manually.
- [x] Move real data into server.

**Comment by crupest** [comment]
Finally done!
