### ISSUE TITLE
Develop crupest api.

### ISSUE THREAD

**Issue by crupest** [crupest/crupest#4]
# Overview
- [x] Test script with Python locally.
- [x] Test script incorporates into aio script.

# todos
- [x] Basic functions.
- [x] Test.
- [x] ~Wait for dotnet run longer so it can fully start.~
- [x] Fix the not working issue.
